//! Word embedding training library.
//!
//! This crate provides tools for training word embeddings from scratch
//! using SkipGram, CBOW, and other models. It supports:
//!
//! - Mini-batch training with gradient clipping and L2 regularization
//! - Learning rate scheduling (constant, exponential, step, cosine)
//! - Early stopping and evaluation metrics
//! - Text preprocessing (HTML stripping, URL removal, contraction expansion)
//! - BPE subword tokenization
//! - Export to Word2Vec, NumPy, ONNX, and binary formats
//! - Semantic search, analogy solving, and embedding arithmetic
//! - Incremental vocabulary updates and LSH-based approximate nearest neighbors
//!
//! # Example
//!
//! ```rust
//! use embedding::*;
//!
//! let text = "the cat sat on the mat";
//! let sentences = load_text_data(text);
//! let (vocab, reverse_vocab) = build_vocab(&sentences);
//! let data = TrainingData { sentences, vocab, reverse_vocab };
//!
//! let config = TrainingConfig {
//!     embedding_dim: 8,
//!     learning_rate: 0.1,
//!     epochs: 2,
//!     batch_size: 4,
//!     context_window: 2,
//!     negative_samples: 2,
//!     model_type: ModelType::SkipGram,
//!     lr_schedule: LearningRateSchedule::Constant,
//!     early_stopping: None,
//!     l2_regularization: None,
//!     dropout_rate: None,
//!     gradient_clip: None,
//! };
//!
//! let mut model = EmbeddingModel::new(config, data.vocab.len());
//! model.train(&data).unwrap();
//! ```

use ndarray::{Array, Array2, Array1};
use ndarray_rand::rand_distr::Uniform;
use rand::Rng;
use rand::prelude::SliceRandom;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use tracing::info;

/// Low-level ONNX protobuf definitions generated by prost.
pub mod onnx {
    include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
}

/// Training hyperparameters for embedding models.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrainingConfig {
    pub embedding_dim: usize,
    pub learning_rate: f64,
    pub epochs: usize,
    pub batch_size: usize,
    pub context_window: usize,
    pub negative_samples: usize,
    pub model_type: ModelType,
    pub lr_schedule: LearningRateSchedule,
    pub early_stopping: Option<EarlyStoppingConfig>,
    pub l2_regularization: Option<f64>,
    pub dropout_rate: Option<f32>,
    pub gradient_clip: Option<f32>,
}

/// Learning rate schedule variants.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum LearningRateSchedule {
    Constant,
    Exponential { decay_rate: f64 },
    Step { step_size: usize, gamma: f64 },
    Cosine { t_max: usize },
}

/// Configuration for early stopping during training.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EarlyStoppingConfig {
    pub patience: usize,
    pub min_delta: f64,
}

/// Supported embedding model architectures.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ModelType {
    SkipGram,
    Cbow,
    SentenceBERT,
}

/// Container for tokenized sentences and the vocabulary mapping.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrainingData {
    pub sentences: Vec<Vec<String>>,
    pub vocab: HashMap<String, usize>,
    pub reverse_vocab: Vec<String>,
}

/// Word embedding model with trained vector representations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbeddingModel {
    #[serde(with = "embeddings_serializer")]
    pub embeddings: Array2<f32>,
    pub config: TrainingConfig,
    pub vocab_size: usize,
    pub memory_mapped: bool,
}

/// Utility for batching and streaming sentence data.
#[derive(Debug, Clone)]
pub struct DataLoader {
    pub batch_size: usize,
    pub shuffle: bool,
    pub use_memory_mapping: bool,
    pub file_path: Option<String>,
}

impl DataLoader {
    /// Creates a new data loader with the given batch size and options.
    pub fn new(batch_size: usize, shuffle: bool, use_memory_mapping: bool) -> Self {
        Self {
            batch_size,
            shuffle,
            use_memory_mapping,
            file_path: None,
        }
    }
    
    /// Sets the file path for lazy loading.
    pub fn set_file_path(&mut self, path: String) {
        self.file_path = Some(path);
    }
    
    /// Groups sentences into fixed-size batches.
    pub fn load_batches(&self, sentences: &[Vec<String>]) -> Vec<Vec<Vec<String>>> {
        let mut batches = Vec::new();
        let mut current_batch = Vec::new();
        
        for sentence in sentences {
            current_batch.push(sentence.clone());
            
            if current_batch.len() >= self.batch_size {
                if self.shuffle {
                    let mut rng = rand::thread_rng();
                    current_batch.shuffle(&mut rng);
                }
                batches.push(current_batch.clone());
                current_batch.clear();
            }
        }
        
        // Add remaining sentences as the last batch
        if !current_batch.is_empty() {
            if self.shuffle {
                let mut rng = rand::thread_rng();
                current_batch.shuffle(&mut rng);
            }
            batches.push(current_batch);
        }
        
        batches
    }
    
    /// Loads sentences from a file, optionally with memory mapping.
    pub fn load_lazily(&self, file_path: &str) -> Result<Vec<Vec<String>>, String> {
        if self.use_memory_mapping {
            self.load_with_memory_mapping(file_path)
        } else {
            self.load_regular(file_path)
        }
    }
    
    fn load_regular(&self, file_path: &str) -> Result<Vec<Vec<String>>, String> {
        use std::fs::File;
        use std::io::Read;
        
        let mut file = File::open(file_path).map_err(|e| e.to_string())?;
        let mut content = String::new();
        file.read_to_string(&mut content).map_err(|e| e.to_string())?;
        
        Ok(load_text_data(&content))
    }
    
    fn load_with_memory_mapping(&self, file_path: &str) -> Result<Vec<Vec<String>>, String> {
        // For memory-mapped files, we'd typically use a library like memmap2
        // For now, we'll just simulate the behavior
        self.load_regular(file_path)
    }

    /// Returns a lazy iterator over sentences from a file.
    pub fn stream_sentences(&self, file_path: &str) -> Result<Box<dyn Iterator<Item = Vec<String>>>, String> {
        use std::fs::File;
        use std::io::{BufRead, BufReader};

        let file = File::open(file_path).map_err(|e| e.to_string())?;
        let reader = BufReader::new(file);
        let processor = TextProcessor::default();

        let iter = reader.lines().filter_map(move |line| {
            let line = line.ok()?;
            let sentences = processor.process_text(&line);
            if sentences.is_empty() {
                None
            } else {
                Some(sentences.into_iter().flatten().collect::<Vec<String>>())
            }
        });

        Ok(Box::new(iter))
    }
}

mod embeddings_serializer {
    use super::*;
    use serde::{Serialize, Deserialize};

    pub fn serialize<S>(embeddings: &Array2<f32>, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let vec_vec: Vec<Vec<f32>> = embeddings.rows().into_iter()
            .map(|row| row.to_vec())
            .collect();
        vec_vec.serialize(serializer)
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<Array2<f32>, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let vec_vec: Vec<Vec<f32>> = Vec::deserialize(deserializer)?;
        let rows = vec_vec.len();
        if rows == 0 {
            return Ok(Array::zeros((0, 0)));
        }
        let cols = vec_vec[0].len();
        
        let mut data = Vec::with_capacity(rows * cols);
        for row in vec_vec {
            data.extend_from_slice(&row);
        }
        
        Array::from_shape_vec((rows, cols), data)
            .map_err(|serde_err| <D::Error as serde::de::Error>::custom(format!("Invalid array shape: {}", serde_err)))
    }
}

impl EmbeddingModel {
    /// Creates a new embedding model with Xavier-initialized weights.
    pub fn new(config: TrainingConfig, vocab_size: usize) -> Self {
        let mut rng = rand::thread_rng();
        let scale = 1.0 / (config.embedding_dim as f32).sqrt();
        let embeddings = Array::from_shape_fn((vocab_size, config.embedding_dim), |_| {
            rng.gen_range(-0.5..0.5) * scale
        });

        Self {
            embeddings,
            config,
            vocab_size,
            memory_mapped: false,
        }
    }

    /// Creates a new embedding model initialized from a pre-trained Word2Vec file.
    pub fn new_with_pretrained(
        config: TrainingConfig,
        vocab_size: usize,
        data: &TrainingData,
        pretrained_path: &str,
    ) -> Result<Self, String> {
        let (pretrained, pretrained_dim) = Self::load_word2vec_format(pretrained_path)?;
        if pretrained_dim != config.embedding_dim {
            return Err(format!(
                "Pre-trained embedding dimension ({}) does not match config ({})",
                pretrained_dim, config.embedding_dim
            ));
        }

        let mut rng = rand::thread_rng();
        let scale = 1.0 / (config.embedding_dim as f32).sqrt();
        let mut embeddings = Array::from_shape_fn((vocab_size, config.embedding_dim), |_| {
            rng.gen_range(-0.5..0.5) * scale
        });

        let mut loaded_count = 0;
        for (word, word_id) in &data.vocab {
            if let Some(pretrained_vec) = pretrained.get(word) {
                for (i, &val) in pretrained_vec.iter().enumerate() {
                    embeddings[[*word_id, i]] = val;
                }
                loaded_count += 1;
            }
        }

        tracing::info!(
            "Loaded {} pre-trained embeddings out of {} vocabulary words",
            loaded_count,
            vocab_size
        );

        Ok(Self {
            embeddings,
            config,
            vocab_size,
            memory_mapped: false,
        })
    }

    /// Trains the model on the provided data.
    pub fn train(&mut self, data: &TrainingData) -> Result<(), String> {
        match self.config.model_type {
            ModelType::SkipGram => self.train_skipgram(data),
            ModelType::Cbow => self.train_cbow(data),
            ModelType::SentenceBERT => self.train_sentence_bert(data),
        }
    }

    fn train_skipgram(&mut self, data: &TrainingData) -> Result<(), String> {
        let mut rng = rand::thread_rng();
        let mut best_loss = f32::MAX;
        let mut patience_counter = 0;

        for epoch in 0..self.config.epochs {
            info!("Epoch {}/{}", epoch + 1, self.config.epochs);

            let current_lr = self.get_learning_rate(epoch, self.config.epochs);
            info!("Current learning rate: {:.6}", current_lr);

            let mut total_loss = 0.0;
            let mut num_updates = 0;
            let mut batch_count = 0;
            let mut batch_loss = 0.0;
            let mut num_batches = 0;
            let mut accum = self.new_gradient_accumulator();

            for sentence in data.sentences.iter() {
                for (target_idx, target_word) in sentence.iter().enumerate() {
                    if let Some(&target_id) = data.vocab.get(target_word) {
                        let start = target_idx.saturating_sub(self.config.context_window);
                        let end = std::cmp::min(target_idx + self.config.context_window + 1, sentence.len());

                        // Get negative samples
                        let negative_samples = get_negative_samples(
                            self.vocab_size,
                            self.config.negative_samples,
                            target_id,
                            &mut rng
                        );

                        for (context_idx, context_word) in sentence.iter().enumerate().skip(start).take(end - start) {
                            if context_idx != target_idx
                                && let Some(&context_id) = data.vocab.get(context_word) {
                                    let loss = self.compute_skipgram_gradients(
                                        target_id, context_id, &negative_samples, current_lr, &mut accum
                                    );
                                    total_loss += loss;
                                    batch_loss += loss;
                                    num_updates += 1;
                                    batch_count += 1;

                                    if batch_count >= self.config.batch_size {
                                        self.apply_gradient_batch(&mut accum, batch_count);
                                        num_batches += 1;
                                        if num_batches % 10 == 0 {
                                            info!("  Batch {} avg loss: {:.4}", num_batches, batch_loss / batch_count as f32);
                                        }
                                        batch_loss = 0.0;
                                        batch_count = 0;
                                    }
                                }
                        }
                    }
                }
            }

            // Apply any remaining gradients
            if batch_count > 0 {
                self.apply_gradient_batch(&mut accum, batch_count);
            }

            let avg_loss = total_loss / num_updates.max(1) as f32;
            info!("Epoch {} completed. Average loss: {:.4}", epoch + 1, avg_loss);

            // Early stopping check
            if self.should_early_stop(epoch + 1, avg_loss, best_loss, &mut patience_counter) {
                info!("Early stopping triggered at epoch {}", epoch + 1);
                break;
            }

            if avg_loss < best_loss {
                best_loss = avg_loss;
                patience_counter = 0;
            }
        }

        Ok(())
    }

    fn train_cbow(&mut self, data: &TrainingData) -> Result<(), String> {
        let mut rng = rand::thread_rng();
        let mut best_loss = f32::MAX;
        let mut patience_counter = 0;

        for epoch in 0..self.config.epochs {
            info!("Epoch {}/{}", epoch + 1, self.config.epochs);

            let current_lr = self.get_learning_rate(epoch, self.config.epochs);
            info!("Current learning rate: {:.6}", current_lr);

            let mut total_loss = 0.0;
            let mut num_updates = 0;
            let mut batch_count = 0;
            let mut batch_loss = 0.0;
            let mut num_batches = 0;
            let mut accum = self.new_gradient_accumulator();

            for sentence in data.sentences.iter() {
                for (target_idx, target_word) in sentence.iter().enumerate() {
                    if let Some(&target_id) = data.vocab.get(target_word) {
                        let start = target_idx.saturating_sub(self.config.context_window);
                        let end = std::cmp::min(target_idx + self.config.context_window + 1, sentence.len());

                        let mut context_ids = Vec::new();
                        for (context_idx, context_word) in sentence.iter().enumerate().skip(start).take(end - start) {
                            if context_idx != target_idx
                                && let Some(&context_id) = data.vocab.get(context_word) {
                                    context_ids.push(context_id);
                                }
                        }

                        if !context_ids.is_empty() {
                            // Get negative samples
                            let negative_samples = get_negative_samples(
                                self.vocab_size,
                                self.config.negative_samples,
                                target_id,
                                &mut rng
                            );

                            let loss = self.compute_cbow_gradients(
                                target_id, &context_ids, &negative_samples, current_lr, &mut accum
                            );
                            total_loss += loss;
                            batch_loss += loss;
                            num_updates += 1;
                            batch_count += 1;

                            if batch_count >= self.config.batch_size {
                                self.apply_gradient_batch(&mut accum, batch_count);
                                num_batches += 1;
                                if num_batches % 10 == 0 {
                                    info!("  Batch {} avg loss: {:.4}", num_batches, batch_loss / batch_count as f32);
                                }
                                batch_loss = 0.0;
                                batch_count = 0;
                            }
                        }
                    }
                }
            }

            // Apply any remaining gradients
            if batch_count > 0 {
                self.apply_gradient_batch(&mut accum, batch_count);
            }

            let avg_loss = total_loss / num_updates.max(1) as f32;
            info!("Epoch {} completed. Average loss: {:.4}", epoch + 1, avg_loss);

            // Early stopping check
            if self.should_early_stop(epoch + 1, avg_loss, best_loss, &mut patience_counter) {
                info!("Early stopping triggered at epoch {}", epoch + 1);
                break;
            }

            if avg_loss < best_loss {
                best_loss = avg_loss;
                patience_counter = 0;
            }
        }

        Ok(())
    }

    fn train_sentence_bert(&mut self, data: &TrainingData) -> Result<(), String> {
        info!("Training Sentence-BERT model (simplified implementation)");
        
        // For Sentence-BERT style training, we'll use a mean pooling approach
        for epoch in 0..self.config.epochs {
            info!("Epoch {}/{}", epoch + 1, self.config.epochs);
            
            for sentence in data.sentences.iter() {
                let word_ids: Vec<usize> = sentence.iter()
                    .filter_map(|word| data.vocab.get(word))
                    .copied()
                    .collect();
                
                if !word_ids.is_empty() {
                    // Simple mean pooling for sentence embeddings
                    let mean_embedding = self.mean_pooling(&word_ids);
                    self.update_embeddings_from_mean(mean_embedding, &word_ids);
                }
            }
        }
        
        Ok(())
    }

    fn mean_pooling(&self, word_ids: &[usize]) -> Array1<f32> {
        let mut sum = Array::zeros(self.config.embedding_dim);
        let mut count = 0;
        
        for &word_id in word_ids {
            if word_id < self.vocab_size {
                let embedding = self.embeddings.row(word_id);
                sum = sum + embedding;
                count += 1;
            }
        }
        
        if count > 0 {
            sum / count as f32
        } else {
            Array::zeros(self.config.embedding_dim)
        }
    }

    fn update_embeddings_from_mean(&mut self, mean_embedding: Array1<f32>, word_ids: &[usize]) {
        for &word_id in word_ids {
            if word_id < self.vocab_size {
                let mut word_embedding = self.embeddings.row_mut(word_id);
                // Move towards the mean embedding
                for i in 0..self.config.embedding_dim {
                    word_embedding[i] += 0.01 * (mean_embedding[i] - word_embedding[i]);
                }
            }
        }
    }

    fn new_gradient_accumulator(&self) -> HashMap<usize, Vec<f32>> {
        HashMap::new()
    }

    fn accumulate_gradient(&self, accum: &mut HashMap<usize, Vec<f32>>, word_id: usize, grad: f32, dim_idx: usize) {
        accum.entry(word_id)
            .or_insert_with(|| vec![0.0; self.config.embedding_dim])[dim_idx] += grad;
    }

    fn apply_gradient_batch(&mut self, accum: &mut HashMap<usize, Vec<f32>>, batch_size: usize) {
        let scale = 1.0 / batch_size.max(1) as f32;
        for (&word_id, grads) in accum.iter() {
            for (i, &grad) in grads.iter().enumerate() {
                self.embeddings[[word_id, i]] -= self.clip_gradient(grad * scale);
            }
        }
        accum.clear();
    }

    fn compute_skipgram_gradients(
        &self,
        target_id: usize,
        context_id: usize,
        negative_samples: &[usize],
        learning_rate: f32,
        accum: &mut HashMap<usize, Vec<f32>>,
    ) -> f32 {
        let target_embedding: Vec<f32> = self.embeddings.row(target_id).to_vec();
        let context_embedding: Vec<f32> = self.embeddings.row(context_id).to_vec();

        let dot_product: f32 = target_embedding.iter().zip(context_embedding.iter()).map(|(&a, &b)| a * b).sum();
        let prob_positive = sigmoid(dot_product);
        let grad_positive = prob_positive - 1.0;

        for i in 0..self.config.embedding_dim {
            let mut grad = learning_rate * grad_positive * context_embedding[i];
            if let Some(l2_reg) = self.config.l2_regularization {
                grad += learning_rate * l2_reg as f32 * target_embedding[i];
            }
            self.accumulate_gradient(accum, target_id, grad, i);

            let mut grad_context = learning_rate * grad_positive * target_embedding[i];
            if let Some(l2_reg) = self.config.l2_regularization {
                grad_context += learning_rate * l2_reg as f32 * context_embedding[i];
            }
            self.accumulate_gradient(accum, context_id, grad_context, i);
        }

        for &neg_id in negative_samples {
            let neg_embedding: Vec<f32> = self.embeddings.row(neg_id).to_vec();
            let dot_product_neg: f32 = target_embedding.iter().zip(neg_embedding.iter()).map(|(&a, &b)| a * b).sum();
            let prob_negative = sigmoid(dot_product_neg);
            let grad_negative = prob_negative;

            for i in 0..self.config.embedding_dim {
                let mut grad = learning_rate * grad_negative * neg_embedding[i];
                if let Some(l2_reg) = self.config.l2_regularization {
                    grad += learning_rate * l2_reg as f32 * target_embedding[i];
                }
                self.accumulate_gradient(accum, target_id, grad, i);

                let mut grad_neg = learning_rate * grad_negative * target_embedding[i];
                if let Some(l2_reg) = self.config.l2_regularization {
                    grad_neg += learning_rate * l2_reg as f32 * neg_embedding[i];
                }
                self.accumulate_gradient(accum, neg_id, grad_neg, i);
            }
        }

        let mut loss = -prob_positive.ln();
        for &neg_id in negative_samples {
            let neg_embedding: Vec<f32> = self.embeddings.row(neg_id).to_vec();
            let dot_product_neg: f32 = target_embedding.iter().zip(neg_embedding.iter()).map(|(&a, &b)| a * b).sum();
            loss += -sigmoid(-dot_product_neg).ln();
        }
        loss
    }

    fn compute_cbow_gradients(
        &self,
        target_id: usize,
        context_ids: &[usize],
        negative_samples: &[usize],
        learning_rate: f32,
        accum: &mut HashMap<usize, Vec<f32>>,
    ) -> f32 {
        let mut context_vector = Array::zeros(self.config.embedding_dim);
        let mut context_embeddings: Vec<Vec<f32>> = Vec::new();

        for &context_id in context_ids {
            let context_embedding: Vec<f32> = self.embeddings.row(context_id).to_vec();
            context_embeddings.push(context_embedding.clone());
            let context_arr = Array::from_shape_vec((self.config.embedding_dim,), context_embedding).unwrap();
            context_vector += &context_arr;
        }
        context_vector /= context_ids.len() as f32;

        let target_embedding: Vec<f32> = self.embeddings.row(target_id).to_vec();
        let target_arr = Array::from_shape_vec((self.config.embedding_dim,), target_embedding.clone()).unwrap();
        let dot_product = context_vector.dot(&target_arr);
        let prob_positive = sigmoid(dot_product);
        let grad_positive = prob_positive - 1.0;

        for (context_idx, &context_id) in context_ids.iter().enumerate() {
            let _context_embedding = &context_embeddings[context_idx];
            for (i, &target_val) in target_embedding.iter().enumerate() {
                let mut grad = learning_rate * grad_positive * target_val;
                if let Some(l2_reg) = self.config.l2_regularization {
                    grad += learning_rate * l2_reg as f32 * self.embeddings[[context_id, i]];
                }
                self.accumulate_gradient(accum, context_id, grad, i);
            }
        }

        for (i, &context_val) in context_vector.iter().enumerate() {
            let mut grad = learning_rate * grad_positive * context_val;
            if let Some(l2_reg) = self.config.l2_regularization {
                grad += learning_rate * l2_reg as f32 * target_embedding[i];
            }
            self.accumulate_gradient(accum, target_id, grad, i);
        }

        for &neg_id in negative_samples {
            let neg_embedding: Vec<f32> = self.embeddings.row(neg_id).to_vec();
            let neg_arr = Array::from_shape_vec((self.config.embedding_dim,), neg_embedding.clone()).unwrap();
            let dot_product_neg = context_vector.dot(&neg_arr);
            let prob_negative = sigmoid(dot_product_neg);
            let grad_negative = prob_negative;

            for &context_id in context_ids {
                for (i, &neg_val) in neg_embedding.iter().enumerate() {
                    let mut grad = learning_rate * grad_negative * neg_val;
                    if let Some(l2_reg) = self.config.l2_regularization {
                        grad += learning_rate * l2_reg as f32 * self.embeddings[[context_id, i]];
                    }
                    self.accumulate_gradient(accum, context_id, grad, i);
                }
            }

            for (i, &context_val) in context_vector.iter().enumerate() {
                let mut grad = learning_rate * grad_negative * context_val;
                if let Some(l2_reg) = self.config.l2_regularization {
                    grad += learning_rate * l2_reg as f32 * neg_embedding[i];
                }
                self.accumulate_gradient(accum, neg_id, grad, i);
            }
        }

        let mut loss = -prob_positive.ln();
        for &neg_id in negative_samples {
            let neg_embedding: Vec<f32> = self.embeddings.row(neg_id).to_vec();
            let neg_arr = Array::from_shape_vec((self.config.embedding_dim,), neg_embedding.clone()).unwrap();
            let dot_product_neg = context_vector.dot(&neg_arr);
            loss += -sigmoid(-dot_product_neg).ln();
        }
        loss
    }

    /// Returns the embedding vector for a given word.
    pub fn get_embedding(&self, word: &str, data: &TrainingData) -> Option<Array1<f32>> {
        if let Some(&word_id) = data.vocab.get(word) {
            Some(self.embeddings.row(word_id).to_owned())
        } else {
            None
        }
    }

    /// Saves embeddings as a JSON file.
    pub fn save_embeddings(&self, path: &str, data: &TrainingData) -> Result<(), String> {
        use std::fs::File;
        use std::io::Write;

        let mut file = File::create(path).map_err(|e| e.to_string())?;

        for (word_id, word) in data.reverse_vocab.iter().enumerate() {
            let embedding = self.embeddings.row(word_id);
            let embedding_str = embedding.iter()
                .map(|&x| x.to_string())
                .collect::<Vec<_>>()
                .join(",");

            writeln!(file, "{}\t{}", word, embedding_str).map_err(|e| e.to_string())?;
        }

        Ok(())
    }

    /// Saves embeddings in the Word2Vec/Gensim text format.
    pub fn save_word2vec_format(&self, path: &str, data: &TrainingData) -> Result<(), String> {
        use std::fs::File;
        use std::io::Write;

        let mut file = File::create(path).map_err(|e| e.to_string())?;
        let vocab_size = data.reverse_vocab.len();
        let dim = self.config.embedding_dim;

        writeln!(file, "{} {}", vocab_size, dim).map_err(|e| e.to_string())?;

        for (word_id, word) in data.reverse_vocab.iter().enumerate() {
            let embedding = self.embeddings.row(word_id);
            let values: Vec<String> = embedding.iter().map(|&x| format!("{:.6}", x)).collect();
            writeln!(file, "{} {}", word, values.join(" ")).map_err(|e| e.to_string())?;
        }

        Ok(())
    }

    /// Loads embeddings from a Word2Vec/Gensim text format file.
    pub fn load_word2vec_format(path: &str) -> Result<(HashMap<String, Vec<f32>>, usize), String> {
        use std::fs::File;
        use std::io::{BufRead, BufReader};

        let file = File::open(path).map_err(|e| e.to_string())?;
        let reader = BufReader::new(file);
        let mut lines = reader.lines();

        let header = lines.next()
            .ok_or("Empty file")?
            .map_err(|e| e.to_string())?;
        let parts: Vec<&str> = header.split_whitespace().collect();
        if parts.len() != 2 {
            return Err("Invalid header format".to_string());
        }
        let _vocab_size: usize = parts[0].parse().map_err(|_| "Invalid vocab size")?;
        let dim: usize = parts[1].parse().map_err(|_| "Invalid dimension")?;

        let mut embeddings = HashMap::new();
        for line in lines {
            let line = line.map_err(|e| e.to_string())?;
            let mut parts = line.split_whitespace();
            let word = parts.next().ok_or("Missing word")?.to_string();
            let values: Result<Vec<f32>, _> = parts.map(|s| s.parse()).collect();
            let values = values.map_err(|_| "Invalid float value")?;
            if values.len() != dim {
                return Err(format!("Expected {} dimensions, got {}", dim, values.len()));
            }
            embeddings.insert(word, values);
        }

        Ok((embeddings, dim))
    }

    /// Saves embeddings as a NumPy `.npy` file for TensorFlow/PyTorch compatibility.
    pub fn save_numpy_format(&self, path: &str, data: &TrainingData) -> Result<(), String> {
        use std::fs::File;
        use std::io::Write;

        let mut file = File::create(path).map_err(|e| e.to_string())?;
        let rows = data.reverse_vocab.len();
        let cols = self.config.embedding_dim;

        // NumPy .npy format header (simplified version 1.0)
        let header = format!(
            "{{'descr': '<f4', 'fortran_order': False, 'shape': ({}, {}), }}",
            rows, cols
        );
        let header_bytes = header.as_bytes();
        let header_len = header_bytes.len();
        let padding = (64 - (header_len + 10) % 64) % 64;

        file.write_all(b"\x93NUMPY\x01\x00").map_err(|e| e.to_string())?;
        let total_len = (header_len + padding) as u16;
        file.write_all(&total_len.to_le_bytes()).map_err(|e| e.to_string())?;
        file.write_all(header_bytes).map_err(|e| e.to_string())?;
        for _ in 0..padding {
            file.write_all(b" ").map_err(|e| e.to_string())?;
        }

        for (word_id, _) in data.reverse_vocab.iter().enumerate() {
            let embedding = self.embeddings.row(word_id);
            for &val in embedding.iter() {
                file.write_all(&val.to_le_bytes()).map_err(|e| e.to_string())?;
            }
        }

        Ok(())
    }

    /// Saves embeddings as an ONNX model with a Gather node for lookup.
    pub fn save_onnx_format(&self, path: &str, data: &TrainingData) -> Result<(), String> {
        use std::fs::File;
        use std::io::Write;
        use prost::Message;
        use onnx::*;

        let vocab_size = data.reverse_vocab.len() as i64;
        let dim = self.config.embedding_dim as i64;

        // Flatten embeddings into raw little-endian f32 bytes
        let mut raw_data = Vec::with_capacity((vocab_size as usize) * (dim as usize) * 4);
        for (word_id, _) in data.reverse_vocab.iter().enumerate() {
            let row = self.embeddings.row(word_id);
            for &val in row.iter() {
                raw_data.extend_from_slice(&val.to_le_bytes());
            }
        }

        let embedding_tensor = TensorProto {
            dims: vec![vocab_size, dim],
            data_type: TensorProtoDataType::Float as i32,
            raw_data,
            name: "embeddings".to_string(),
        };

        let gather_node = NodeProto {
            input: vec!["embeddings".to_string(), "input_indices".to_string()],
            output: vec!["output".to_string()],
            name: "gather_embeddings".to_string(),
            op_type: "Gather".to_string(),
            domain: "".to_string(),
        };

        let input_type = TypeProto {
            tensor_type: Some(TensorProto {
                dims: vec![-1], // dynamic batch size
                data_type: TensorProtoDataType::Int64 as i32,
                raw_data: vec![],
                name: "".to_string(),
            }),
        };
        let output_type = TypeProto {
            tensor_type: Some(TensorProto {
                dims: vec![-1, dim],
                data_type: TensorProtoDataType::Float as i32,
                raw_data: vec![],
                name: "".to_string(),
            }),
        };

        let graph = GraphProto {
            node: vec![gather_node],
            input: vec![
                ValueInfoProto {
                    name: "input_indices".to_string(),
                    r#type: Some(input_type),
                },
            ],
            output: vec![
                ValueInfoProto {
                    name: "output".to_string(),
                    r#type: Some(output_type),
                },
            ],
            initializer: vec![embedding_tensor],
            name: "embedding_graph".to_string(),
        };

        let opset = OperatorSetIdProto {
            domain: "".to_string(),
            version: 9,
        };

        let model = ModelProto {
            ir_version: 9,
            producer_name: "embedding-trainer".to_string(),
            producer_version: env!("CARGO_PKG_VERSION").to_string(),
            domain: "".to_string(),
            graph: Some(graph),
            opset_import: vec![opset],
        };

        let mut buf = Vec::new();
        model.encode(&mut buf).map_err(|e| e.to_string())?;

        let mut file = File::create(path).map_err(|e| e.to_string())?;
        file.write_all(&buf).map_err(|e| e.to_string())?;

        Ok(())
    }

    /// Returns the top-k most similar words to the query using full cosine similarity.
    pub fn semantic_search(&self, query: &str, data: &TrainingData, top_k: usize) -> Vec<(String, f32)> {
        let query_emb = match self.get_embedding(query, data) {
            Some(e) => e,
            None => return Vec::new(),
        };

        let mut results = Vec::new();
        for (word_id, word) in data.reverse_vocab.iter().enumerate() {
            if word == query {
                continue;
            }
            let candidate = self.embeddings.row(word_id);
            let dot: f32 = query_emb.iter().zip(candidate.iter()).map(|(&a, &b)| a * b).sum();
            let norm_query = query_emb.iter().map(|&x| x * x).sum::<f32>().sqrt();
            let norm_candidate = candidate.iter().map(|&x| x * x).sum::<f32>().sqrt();
            if norm_query > 0.0 && norm_candidate > 0.0 {
                results.push((word.clone(), dot / (norm_query * norm_candidate)));
            }
        }

        results.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        results.into_iter().take(top_k).collect()
    }

    /// Computes the vector difference `emb(word1) - emb(word2)`.
    pub fn embedding_arithmetic(&self, word1: &str, word2: &str, data: &TrainingData) -> Option<Array1<f32>> {
        let emb1 = self.get_embedding(word1, data)?;
        let emb2 = self.get_embedding(word2, data)?;
        Some(&emb1 - &emb2)
    }

    /// Linearly interpolates between two word embeddings.
    pub fn interpolate_embeddings(&self, word1: &str, word2: &str, data: &TrainingData, alpha: f32) -> Option<Array1<f32>> {
        let emb1 = self.get_embedding(word1, data)?;
        let emb2 = self.get_embedding(word2, data)?;
        Some(&emb1 * alpha + &emb2 * (1.0 - alpha))
    }

    /// Cosine similarity between two words in the learned embedding space.
    pub fn similarity(&self, word1: &str, word2: &str, data: &TrainingData) -> Option<f32> {
        let emb1 = self.get_embedding(word1, data)?;
        let emb2 = self.get_embedding(word2, data)?;
        
        let dot_product = emb1.iter().zip(emb2.iter()).map(|(&a, &b)| a * b).sum::<f32>();
        let norm1 = emb1.iter().map(|&x| x * x).sum::<f32>().sqrt();
        let norm2 = emb2.iter().map(|&x| x * x).sum::<f32>().sqrt();
        
        if norm1 == 0.0 || norm2 == 0.0 {
            None
        } else {
            Some(dot_product / (norm1 * norm2))
        }
    }
    
    /// Evaluates the model against synthetic validation pairs and analogies.
    pub fn evaluate(&self, data: &TrainingData, validation_data: &ValidationData) -> EvaluationMetrics {
        let mut correct_pairs = 0;
        let mut total_pairs = 0;
        let mut total_similarity = 0.0;
        let mut similarities = Vec::new();
        
        // Evaluate word similarity
        for (word1, word2) in validation_data.positive_pairs.iter() {
            if let Some(sim) = self.similarity(word1, word2, data) {
                similarities.push(sim);
                total_similarity += sim;
                correct_pairs += 1;
            }
            total_pairs += 1;
        }
        
        for (word1, word2) in validation_data.negative_pairs.iter() {
            if let Some(sim) = self.similarity(word1, word2, data) {
                similarities.push(sim);
                total_similarity += sim;
                correct_pairs += 1;
            }
            total_pairs += 1;
        }
        
        let accuracy = if total_pairs > 0 { correct_pairs as f32 / total_pairs as f32 } else { 0.0 };
        let mean_similarity = if !similarities.is_empty() { total_similarity / similarities.len() as f32 } else { 0.0 };
        
        // Calculate embedding quality score based on various metrics
        let embedding_quality_score = self.calculate_embedding_quality(data);
        
        EvaluationMetrics {
            accuracy,
            precision: accuracy,  // Simplified for now
            recall: accuracy,     // Simplified for now
            f1_score: accuracy,  // Simplified for now
            mean_similarity,
            embedding_quality_score,
        }
    }
    
    fn calculate_embedding_quality(&self, data: &TrainingData) -> f32 {
        let mut total_norm = 0.0;
        let mut count = 0;
        let mut total_variance = 0.0;
        
        for (word_id, _) in data.reverse_vocab.iter().enumerate() {
            let embedding = self.embeddings.row(word_id);
            let norm = embedding.iter().map(|&x| x * x).sum::<f32>().sqrt();
            total_norm += norm;
            count += 1;
            
            // Calculate variance within embedding dimensions
            let mean_val = embedding.sum() / self.config.embedding_dim as f32;
            let variance = embedding.iter().map(|&x| (x - mean_val).powi(2)).sum::<f32>() / self.config.embedding_dim as f32;
            total_variance += variance;
        }
        
        let avg_norm = if count > 0 { total_norm / count as f32 } else { 0.0 };
        let avg_variance = if count > 0 { total_variance / count as f32 } else { 0.0 };
        
        // Quality score based on norm and variance (higher is better)
        let quality = (avg_norm * avg_variance).sqrt();
        quality.min(1.0)  // Normalize to 0-1
    }

    /// L2-normalizes every embedding vector to unit length.
    pub fn normalize_embeddings(&mut self) {
        for mut row in self.embeddings.rows_mut() {
            let norm = row.iter().map(|&x| x * x).sum::<f32>().sqrt();
            if norm > 0.0 {
                row.map_inplace(|x| *x /= norm);
            }
        }
    }

    /// Solves word analogies of the form `word1 : word2 :: word3 : ?`.
    pub fn analogy(&self, word1: &str, word2: &str, word3: &str, data: &TrainingData, top_k: usize) -> Vec<(String, f32)> {
        let emb1 = match self.get_embedding(word1, data) {
            Some(e) => e,
            None => return Vec::new(),
        };
        let emb2 = match self.get_embedding(word2, data) {
            Some(e) => e,
            None => return Vec::new(),
        };
        let emb3 = match self.get_embedding(word3, data) {
            Some(e) => e,
            None => return Vec::new(),
        };

        let target = &emb3 + &emb1 - &emb2;
        let mut results = Vec::new();

        for (word_id, word) in data.reverse_vocab.iter().enumerate() {
            if word == word1 || word == word2 || word == word3 {
                continue;
            }
            let candidate = self.embeddings.row(word_id);
            let dot: f32 = target.iter().zip(candidate.iter()).map(|(&a, &b)| a * b).sum();
            let norm_target = target.iter().map(|&x| x * x).sum::<f32>().sqrt();
            let norm_candidate = candidate.iter().map(|&x| x * x).sum::<f32>().sqrt();
            if norm_target > 0.0 && norm_candidate > 0.0 {
                results.push((word.clone(), dot / (norm_target * norm_candidate)));
            }
        }

        results.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        results.into_iter().take(top_k).collect()
    }

    /// Splits sentences into training and validation sets.
    pub fn split_data(&self, sentences: &[Vec<String>], train_ratio: f64) -> (Vec<Vec<String>>, Vec<Vec<String>>) {
        let total_sentences = sentences.len();
        let train_size = (total_sentences as f64 * train_ratio) as usize;
        
        let mut shuffled_indices: Vec<usize> = (0..total_sentences).collect();
        let mut rng = rand::thread_rng();
        shuffled_indices.shuffle(&mut rng);
        
        let train_sentences: Vec<Vec<String>> = shuffled_indices[..train_size]
            .iter()
            .map(|&i| sentences[i].clone())
            .collect();
        
        let val_sentences: Vec<Vec<String>> = shuffled_indices[train_size..]
            .iter()
            .map(|&i| sentences[i].clone())
            .collect();
        
        (train_sentences, val_sentences)
    }
    
    /// Generates synthetic validation pairs and analogies from sentences.
    pub fn create_validation_data(&self, sentences: &[Vec<String>]) -> ValidationData {
        let mut positive_pairs = Vec::new();
        let mut negative_pairs = Vec::new();
        let mut analogies = Vec::new();
        
        // Simple heuristic to create word pairs
        for sentence in sentences {
            if sentence.len() >= 2 {
                // Consecutive words as positive pairs
                for i in 0..sentence.len() - 1 {
                    positive_pairs.push((sentence[i].clone(), sentence[i + 1].clone()));
                }
                
                // Non-consecutive words as negative pairs
                if sentence.len() >= 3 {
                    for i in 0..sentence.len() - 2 {
                        negative_pairs.push((sentence[i].clone(), sentence[i + 2].clone()));
                    }
                }
            }
        }
        
        // Simple analogies (this is a simplified version)
        if sentences.len() >= 4 {
            for i in 0..std::cmp::min(10, sentences.len() - 3) {
                let s1 = &sentences[i];
                let s2 = &sentences[i + 1];
                let s3 = &sentences[i + 2];
                let s4 = &sentences[i + 3];
                
                if !s1.is_empty() && !s2.is_empty() && !s3.is_empty() && !s4.is_empty() {
                    analogies.push((
                        s1[0].clone(),
                        s2[0].clone(),
                        s3[0].clone(),
                        s4[0].clone(),
                    ));
                }
            }
        }
        
        ValidationData {
            positive_pairs,
            negative_pairs,
            analogies,
        }
    }

    /// Expands the vocabulary and embedding matrix with new words.
    pub fn incremental_vocab_update(
        &mut self,
        new_words: &[String],
        data: &mut TrainingData,
    ) -> Result<Vec<usize>, String> {
        let mut added_ids = Vec::new();
        let mut rng = rand::thread_rng();
        let scale = 1.0 / (self.config.embedding_dim as f32).sqrt();

        for word in new_words {
            if data.vocab.contains_key(word) {
                continue;
            }
            let new_id = data.vocab.len();
            data.vocab.insert(word.clone(), new_id);
            data.reverse_vocab.push(word.clone());
            added_ids.push(new_id);
        }

        if added_ids.is_empty() {
            return Ok(added_ids);
        }

        // Expand embeddings matrix with Xavier initialization for new words
        let new_size = data.vocab.len();
        let mut new_embeddings = Array::from_shape_fn((new_size, self.config.embedding_dim), |_| {
            rng.gen_range(-0.5..0.5) * scale
        });

        // Copy old embeddings
        for i in 0..self.vocab_size {
            for j in 0..self.config.embedding_dim {
                new_embeddings[[i, j]] = self.embeddings[[i, j]];
            }
        }

        self.embeddings = new_embeddings;
        self.vocab_size = new_size;

        Ok(added_ids)
    }

    /// Computes a sentence-level embedding by mean-pooling word embeddings.
    pub fn sentence_embedding(&self, sentence: &[String], data: &TrainingData) -> Option<Array1<f32>> {
        if sentence.is_empty() {
            return None;
        }
        let mut sum = Array::zeros(self.config.embedding_dim);
        let mut count = 0usize;
        for word in sentence {
            if let Some(emb) = self.get_embedding(word, data) {
                sum += &emb;
                count += 1;
            }
        }
        if count == 0 {
            return None;
        }
        Some(&sum / (count as f32))
    }
}

/// Combines text embeddings with auxiliary vectors (e.g., image features).
#[derive(Debug, Clone)]
pub struct MultimodalFusion {
    pub text_dim: usize,
    pub aux_dim: usize,
}

impl MultimodalFusion {
    /// Concatenates a text embedding with an auxiliary vector.
    pub fn concatenate(&self, text: &Array1<f32>, aux: &Array1<f32>) -> Array1<f32> {
        let mut result = Array::zeros(self.text_dim + self.aux_dim);
        result.slice_mut(ndarray::s![..self.text_dim]).assign(text);
        result.slice_mut(ndarray::s![self.text_dim..]).assign(aux);
        result
    }

    /// Weighted average of text and auxiliary embeddings.
    /// Both vectors must have the same dimensionality.
    pub fn weighted_average(&self, text: &Array1<f32>, aux: &Array1<f32>, text_weight: f32) -> Option<Array1<f32>> {
        if text.len() != aux.len() {
            return None;
        }
        let aux_weight = 1.0 - text_weight;
        Some(text * text_weight + aux * aux_weight)
    }
}

/// Linear alignment of embeddings across languages using a projection matrix.
#[derive(Debug, Clone)]
pub struct CrossLingualAligner {
    pub projection: Array2<f32>,
}

impl CrossLingualAligner {
    /// Creates an aligner with an identity-initialized projection matrix.
    pub fn new(dim: usize) -> Self {
        let mut proj = Array::zeros((dim, dim));
        for i in 0..dim {
            proj[[i, i]] = 1.0;
        }
        Self { projection: proj }
    }

    /// Projects a source-language embedding into the target-language space.
    pub fn align(&self, embedding: &Array1<f32>) -> Array1<f32> {
        self.projection.dot(embedding)
    }

    /// Trains the projection matrix from a list of translation pairs using
    /// least-squares via stochastic gradient descent.
    pub fn train_from_dictionary(
        &mut self,
        pairs: &[(Array1<f32>, Array1<f32>)],
        epochs: usize,
        learning_rate: f32,
    ) {
        let dim = self.projection.nrows();
        for _ in 0..epochs {
            for (src, tgt) in pairs {
                let pred = self.projection.dot(src);
                let error = &pred - tgt;
                for i in 0..dim {
                    let grad = error[i] * src;
                    let mut row = self.projection.row_mut(i);
                    row -= &(grad * learning_rate);
                }
            }
        }
    }
}

/// Adapts a general embedding model to a specific domain by fine-tuning
/// on domain sentences with an optional domain-vocabulary boost.
pub struct DomainAdapter;

impl DomainAdapter {
    /// Fine-tunes a model on domain-specific sentences for a small number of epochs.
    pub fn adapt(
        model: &mut EmbeddingModel,
        data: &mut TrainingData,
        domain_sentences: &[Vec<String>],
        epochs: usize,
    ) -> Result<(), String> {
        let mut domain_data = TrainingData {
            sentences: domain_sentences.to_vec(),
            vocab: data.vocab.clone(),
            reverse_vocab: data.reverse_vocab.clone(),
        };
        // Incremental vocab update for any new domain words
        let domain_words: Vec<String> = domain_sentences
            .iter()
            .flat_map(|s| s.iter().cloned())
            .collect::<std::collections::HashSet<String>>()
            .into_iter()
            .collect();
        model.incremental_vocab_update(&domain_words, &mut domain_data)?;

        let original_epochs = model.config.epochs;
        model.config.epochs = epochs;
        model.train(&domain_data)?;
        model.config.epochs = original_epochs;

        // Update caller's data to reflect new vocabulary
        *data = domain_data;
        Ok(())
    }
}

/// Produces document-level embeddings by aggregating sentence embeddings.
pub struct DocumentEmbedder;

impl DocumentEmbedder {
    /// Returns a document vector by mean-pooling sentence embeddings.
    pub fn embed_document(
        model: &EmbeddingModel,
        data: &TrainingData,
        sentences: &[Vec<String>],
    ) -> Option<Array1<f32>> {
        if sentences.is_empty() {
            return None;
        }
        let mut sum = Array::zeros(model.config.embedding_dim);
        let mut count = 0usize;
        for sentence in sentences {
            if let Some(emb) = model.sentence_embedding(sentence, data) {
                sum += &emb;
                count += 1;
            }
        }
        if count == 0 {
            return None;
        }
        Some(&sum / (count as f32))
    }
}

/// Zero-shot transfer learning via nearest-neighbor class prototype matching.
pub struct ZeroShotTransfer;

impl ZeroShotTransfer {
    /// Given class prototypes (label -> prototype vector), assigns the nearest
    /// prototype to each query embedding by cosine similarity.
    pub fn classify(
        query: &Array1<f32>,
        class_prototypes: &HashMap<String, Array1<f32>>,
    ) -> Option<(String, f32)> {
        let mut best_label = None;
        let mut best_sim = f32::NEG_INFINITY;
        for (label, proto) in class_prototypes {
            let dot: f32 = query.iter().zip(proto.iter()).map(|(&a, &b)| a * b).sum();
            let norm_q = query.iter().map(|&x| x * x).sum::<f32>().sqrt();
            let norm_p = proto.iter().map(|&x| x * x).sum::<f32>().sqrt();
            if norm_q > 0.0 && norm_p > 0.0 {
                let sim = dot / (norm_q * norm_p);
                if sim > best_sim {
                    best_sim = sim;
                    best_label = Some(label.clone());
                }
            }
        }
        best_label.map(|l| (l, best_sim))
    }
}

/// Expands a search query with top-k similar words from the embedding space.
pub struct QueryExpander;

impl QueryExpander {
    /// Returns the original query word plus its `top_k` most similar neighbors.
    pub fn expand(
        model: &EmbeddingModel,
        data: &TrainingData,
        query: &str,
        top_k: usize,
    ) -> Vec<String> {
        let mut result = vec![query.to_string()];
        let neighbors = model.semantic_search(query, data, top_k);
        for (word, _) in neighbors {
            result.push(word);
        }
        result
    }
}

/// Agglomerative hierarchical clustering of word embeddings.
pub struct HierarchicalClustering;

impl HierarchicalClustering {
    /// Clusters vocabulary words into `num_clusters` groups using average-linkage
    /// agglomerative clustering on cosine similarity.
    pub fn cluster(
        model: &EmbeddingModel,
        data: &TrainingData,
        num_clusters: usize,
    ) -> Vec<Vec<String>> {
        let n = data.reverse_vocab.len();
        if n == 0 {
            return Vec::new();
        }
        let target_clusters = num_clusters.min(n);

        // Initialize each word as its own cluster
        let mut clusters: Vec<Vec<usize>> = (0..n).map(|i| vec![i]).collect();

        while clusters.len() > target_clusters {
            let mut best_pair = (0, 1);
            let mut best_sim = f32::NEG_INFINITY;

            for i in 0..clusters.len() {
                for j in (i + 1)..clusters.len() {
                    let sim = Self::cluster_similarity(model, &clusters[i], &clusters[j]);
                    if sim > best_sim {
                        best_sim = sim;
                        best_pair = (i, j);
                    }
                }
            }

            let (i, j) = best_pair;
            let mut merged = clusters.remove(j);
            clusters[i].append(&mut merged);
        }

        clusters
            .into_iter()
            .map(|ids| ids.into_iter().map(|id| data.reverse_vocab[id].clone()).collect())
            .collect()
    }

    fn cluster_similarity(model: &EmbeddingModel, a: &[usize], b: &[usize]) -> f32 {
        let mut total_sim = 0.0;
        let mut count = 0usize;
        for &i in a {
            let emb_i = model.embeddings.row(i);
            for &j in b {
                let emb_j = model.embeddings.row(j);
                let dot: f32 = emb_i.iter().zip(emb_j.iter()).map(|(&x, &y)| x * y).sum();
                let norm_i = emb_i.iter().map(|&x| x * x).sum::<f32>().sqrt();
                let norm_j = emb_j.iter().map(|&x| x * x).sum::<f32>().sqrt();
                if norm_i > 0.0 && norm_j > 0.0 {
                    total_sim += dot / (norm_i * norm_j);
                    count += 1;
                }
            }
        }
        if count == 0 {
            0.0
        } else {
            total_sim / (count as f32)
        }
    }
}

/// Builds a vocabulary map and reverse lookup from tokenized sentences.
pub fn build_vocab(sentences: &[Vec<String>]) -> (HashMap<String, usize>, Vec<String>) {
    let mut vocab = HashMap::new();
    let mut reverse_vocab = Vec::new();
    let mut vocab_counter = 0;
    
    for sentence in sentences {
        for word in sentence {
            if !vocab.contains_key(word) {
                vocab.insert(word.clone(), vocab_counter);
                reverse_vocab.push(word.clone());
                vocab_counter += 1;
            }
        }
    }
    
    (vocab, reverse_vocab)
}

/// Locality-Sensitive Hashing index for approximate nearest neighbor search.
pub struct LSHIndex {
    pub hash_tables: Vec<std::collections::HashMap<usize, Vec<usize>>>,
    pub hyperplanes: Vec<Vec<Vec<f32>>>,
    pub num_hashes: usize,
    pub embedding_dim: usize,
}

impl LSHIndex {
    /// Creates a new LSH index with random projection hyperplanes.
    pub fn new(num_hashes: usize, embedding_dim: usize) -> Self {
        let mut rng = rand::thread_rng();
        let mut hyperplanes = Vec::with_capacity(num_hashes);
        for _ in 0..num_hashes {
            let mut table_planes = Vec::new();
            for _ in 0..32 {
                let plane: Vec<f32> = (0..embedding_dim)
                    .map(|_| rng.r#gen::<f32>() * 2.0 - 1.0)
                    .collect();
                table_planes.push(plane);
            }
            hyperplanes.push(table_planes);
        }

        let mut hash_tables = Vec::with_capacity(num_hashes);
        for _ in 0..num_hashes {
            hash_tables.push(std::collections::HashMap::new());
        }

        Self {
            hash_tables,
            hyperplanes,
            num_hashes,
            embedding_dim,
        }
    }

    /// Indexes all vocabulary embeddings into the hash tables.
    pub fn build(&mut self, model: &EmbeddingModel, data: &TrainingData) {
        for (word_id, _) in data.reverse_vocab.iter().enumerate() {
            let embedding = model.embeddings.row(word_id);
            for table_id in 0..self.num_hashes {
                let hash = self.compute_hash(&embedding, table_id);
                self.hash_tables[table_id]
                    .entry(hash)
                    .or_default()
                    .push(word_id);
            }
        }
    }

    fn compute_hash(&self, embedding: &ndarray::ArrayView1<f32>, table_id: usize) -> usize {
        let mut hash = 0usize;
        for (bit_idx, plane) in self.hyperplanes[table_id].iter().enumerate() {
            let dot: f32 = embedding.iter().zip(plane.iter()).map(|(&a, &b)| a * b).sum();
            if dot > 0.0 {
                hash |= 1 << bit_idx;
            }
        }
        hash
    }

    /// Approximate top-k nearest neighbors for a query word using LSH.
    pub fn query(&self, query_word: &str, model: &EmbeddingModel, data: &TrainingData, top_k: usize) -> Vec<(String, f32)> {
        let query_emb = match model.get_embedding(query_word, data) {
            Some(e) => e,
            None => return Vec::new(),
        };

        let mut candidate_set = std::collections::HashSet::new();
        for table_id in 0..self.num_hashes {
            let hash = self.compute_hash(&query_emb.view(), table_id);
            if let Some(bucket) = self.hash_tables[table_id].get(&hash) {
                for &word_id in bucket {
                    candidate_set.insert(word_id);
                }
            }
        }

        let mut results = Vec::new();
        for &word_id in &candidate_set {
            let word = &data.reverse_vocab[word_id];
            if word == query_word {
                continue;
            }
            let candidate = model.embeddings.row(word_id);
            let dot: f32 = query_emb.iter().zip(candidate.iter()).map(|(&a, &b)| a * b).sum();
            let norm_query = query_emb.iter().map(|&x| x * x).sum::<f32>().sqrt();
            let norm_candidate = candidate.iter().map(|&x| x * x).sum::<f32>().sqrt();
            if norm_query > 0.0 && norm_candidate > 0.0 {
                results.push((word.clone(), dot / (norm_query * norm_candidate)));
            }
        }

        results.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        results.into_iter().take(top_k).collect()
    }
}

// Helper function for sigmoid activation
fn sigmoid(x: f32) -> f32 {
    1.0 / (1.0 + (-x).exp())
}

// Negative sampling utility
fn get_negative_samples(vocab_size: usize, num_samples: usize, target_id: usize, rng: &mut rand::rngs::ThreadRng) -> Vec<usize> {
    let mut samples = Vec::new();
    let dist = Uniform::new(0, vocab_size);
    
    while samples.len() < num_samples {
        let candidate = rng.sample(dist);
        if candidate != target_id && !samples.contains(&candidate) {
            samples.push(candidate);
        }
    }
    
    samples
}

// Learning rate scheduling
impl EmbeddingModel {
    fn get_learning_rate(&self, epoch: usize, total_epochs: usize) -> f32 {
        match self.config.lr_schedule {
            LearningRateSchedule::Constant => self.config.learning_rate as f32,
            LearningRateSchedule::Exponential { decay_rate } => {
                (self.config.learning_rate * decay_rate.powi(epoch as i32)) as f32
            }
            LearningRateSchedule::Step { step_size, gamma } => {
                let num_steps = epoch / step_size;
                (self.config.learning_rate * gamma.powi(num_steps as i32)) as f32
            }
            LearningRateSchedule::Cosine { t_max } => {
                let t = epoch as f32 / std::cmp::min(t_max, total_epochs) as f32;
                let lr = 0.5 * (1.0 + (std::f32::consts::PI * t).cos());
                self.config.learning_rate as f32 * lr
            }
        }
    }
    
    fn should_early_stop(&self, _epoch: usize, current_loss: f32, best_loss: f32, patience_counter: &mut usize) -> bool {
        if let Some(config) = &self.config.early_stopping {
            if current_loss < best_loss - config.min_delta as f32 {
                *patience_counter = 0;
                false
            } else {
                *patience_counter += 1;
                *patience_counter >= config.patience
            }
        } else {
            false
        }
    }
    
    fn clip_gradient(&self, grad: f32) -> f32 {
        if let Some(max_norm) = self.config.gradient_clip {
            grad.clamp(-max_norm, max_norm)
        } else {
            grad
        }
    }
}

/// Evaluation metrics for a trained embedding model.
#[derive(Debug, Clone)]
pub struct EvaluationMetrics {
    pub accuracy: f32,
    pub precision: f32,
    pub recall: f32,
    pub f1_score: f32,
    pub mean_similarity: f32,
    pub embedding_quality_score: f32,
}

/// Synthetic validation data generated from sentences for evaluation.
#[derive(Debug, Clone)]
pub struct ValidationData {
    pub positive_pairs: Vec<(String, String)>,
    pub negative_pairs: Vec<(String, String)>,
    pub analogies: Vec<(String, String, String, String)>,  // (word1, word2, word3, word4) for word1 - word2 + word3 = word4
}

/// Configurable text preprocessing pipeline.
///
/// Controls lowercasing, punctuation removal, HTML stripping,
/// URL removal, contraction expansion, and stop-word filtering.
#[derive(Debug, Clone)]
pub struct TextProcessor {
    pub lowercase: bool,
    pub remove_punctuation: bool,
    pub remove_numbers: bool,
    pub remove_stop_words: bool,
    pub remove_html: bool,
    pub remove_urls: bool,
    pub expand_contractions: bool,
    pub language: String,
}

impl Default for TextProcessor {
    fn default() -> Self {
        Self {
            lowercase: true,
            remove_punctuation: true,
            remove_numbers: false,
            remove_stop_words: false,
            remove_html: false,
            remove_urls: false,
            expand_contractions: false,
            language: "en".to_string(),
        }
    }
}

impl TextProcessor {
    /// Processes raw text into tokenized sentences according to the configured filters.
    pub fn process_text(&self, text: &str) -> Vec<Vec<String>> {
        let mut text = text.to_string();

        // Remove HTML tags
        if self.remove_html {
            text = Self::strip_html(&text);
        }

        // Remove URLs
        if self.remove_urls {
            text = Self::strip_urls(&text);
        }

        let mut sentences = Vec::new();

        // Split into sentences
        for sentence in text.split(['.', '!', '?', '\n']) {
            if !sentence.trim().is_empty() {
                let mut processed_words = Vec::new();

                // Split into words and process each word
                for word in sentence.split_whitespace() {
                    let processed_word = self.process_word(word);
                    if !processed_word.is_empty() {
                        for subword in processed_word.split_whitespace() {
                            processed_words.push(subword.to_string());
                        }
                    }
                }

                if !processed_words.is_empty() {
                    sentences.push(processed_words);
                }
            }
        }

        sentences
    }

    fn strip_html(text: &str) -> String {
        let mut result = String::new();
        let mut in_tag = false;
        for c in text.chars() {
            if c == '<' {
                in_tag = true;
            } else if c == '>' {
                in_tag = false;
            } else if !in_tag {
                result.push(c);
            }
        }
        result
    }

    fn strip_urls(text: &str) -> String {
        text.split_whitespace()
            .filter(|word| !(word.starts_with("http://") || word.starts_with("https://") || word.starts_with("www.")))
            .collect::<Vec<&str>>()
            .join(" ")
    }

    fn process_word(&self, word: &str) -> String {
        let mut result = word.to_string();

        // Expand contractions
        if self.expand_contractions {
            result = Self::expand_contraction(&result);
        }

        // Convert to lowercase
        if self.lowercase {
            result = result.to_lowercase();
        }

        // Remove punctuation
        if self.remove_punctuation {
            result = result.chars()
                .filter(|c| c.is_alphanumeric() || c.is_whitespace())
                .collect::<String>()
                .trim()
                .to_string();
        }

        // Remove numbers
        if self.remove_numbers {
            result = result.chars()
                .filter(|c| !c.is_ascii_digit())
                .collect::<String>();
        }

        // Remove empty strings
        if result.is_empty() {
            return String::new();
        }

        result
    }

    fn expand_contraction(word: &str) -> String {
        match word.to_lowercase().as_str() {
            "can't" => "cannot".to_string(),
            "won't" => "will not".to_string(),
            "n't" => " not".to_string(),
            "'re" => " are".to_string(),
            "'ve" => " have".to_string(),
            "'ll" => " will".to_string(),
            "'d" => " would".to_string(),
            "'m" => " am".to_string(),
            "i'm" => "i am".to_string(),
            "don't" => "do not".to_string(),
            "doesn't" => "does not".to_string(),
            "didn't" => "did not".to_string(),
            "isn't" => "is not".to_string(),
            "aren't" => "are not".to_string(),
            "wasn't" => "was not".to_string(),
            "weren't" => "were not".to_string(),
            "haven't" => "have not".to_string(),
            "hasn't" => "has not".to_string(),
            "hadn't" => "had not".to_string(),
            "wouldn't" => "would not".to_string(),
            "couldn't" => "could not".to_string(),
            "shouldn't" => "should not".to_string(),
            "let's" => "let us".to_string(),
            "that's" => "that is".to_string(),
            "who's" => "who is".to_string(),
            "what's" => "what is".to_string(),
            "here's" => "here is".to_string(),
            "there's" => "there is".to_string(),
            "where's" => "where is".to_string(),
            "it's" => "it is".to_string(),
            _ => word.to_string(),
        }
    }
    
    /// Simple heuristic-based language detection.
    pub fn detect_language(&self, text: &str) -> String {
        // Simple heuristic for language detection
        // This is a very basic implementation - in practice, you'd use more sophisticated methods
        
        let english_stop_words = ["the", "and", "a", "an", "in", "on", "at", "to", "for", "of", "with", "by", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "do", "does", "did", "will", "would", "shall", "should", "can", "could", "may", "might", "must", "i", "you", "he", "she", "it", "we", "they", "me", "him", "her", "us", "them"];
        
        let words_vec: Vec<&str> = text.split_whitespace().collect();
        let words = &words_vec;
        let mut english_count = 0;
        
        for word in words {
            let lower_word = word.to_lowercase();
            if english_stop_words.contains(&lower_word.as_str()) {
                english_count += 1;
            }
        }
        
        // If more than 20% of words are common English stop words, assume English
        if english_count > words.len() / 5 {
            "en".to_string()
        } else {
            "unknown".to_string()
        }
    }
}

/// Byte Pair Encoding tokenizer with trained merge rules.
#[derive(Debug, Clone)]
#[derive(Default)]
pub struct BPETokenizer {
    pub vocab: HashMap<String, usize>,
    pub merges: Vec<(String, String)>,
    pub vocab_size: usize,
}


impl BPETokenizer {
    /// Trains BPE merge rules from a corpus until the target vocabulary size is reached.
    pub fn train(corpus: &[String], target_vocab_size: usize) -> Self {
        let mut word_freqs: HashMap<Vec<String>, usize> = HashMap::new();

        // Initialize: split words into characters + end-of-word marker
        for word in corpus {
            let cleaned = word.to_lowercase().trim().to_string();
            if cleaned.is_empty() {
                continue;
            }
            let chars: Vec<String> = cleaned.chars().map(|c| c.to_string()).collect();
            let mut tokens = chars;
            tokens.push("</w>".to_string());
            *word_freqs.entry(tokens).or_insert(0) += 1;
        }

        let mut vocab: HashMap<String, usize> = HashMap::new();
        let mut merges: Vec<(String, String)> = Vec::new();

        // Build initial vocabulary from all characters
        let mut all_tokens: Vec<String> = Vec::new();
        for tokens in word_freqs.keys() {
            for token in tokens {
                all_tokens.push(token.clone());
            }
        }
        for token in all_tokens {
            let next_id = vocab.len();
            vocab.entry(token).or_insert(next_id);
        }

        while vocab.len() < target_vocab_size {
            let mut pair_counts: HashMap<(String, String), usize> = HashMap::new();

            for (tokens, freq) in &word_freqs {
                for pair in tokens.windows(2) {
                    let key = (pair[0].clone(), pair[1].clone());
                    *pair_counts.entry(key).or_insert(0) += freq;
                }
            }

            if pair_counts.is_empty() {
                break;
            }

            // Find most frequent pair
            let best_pair = pair_counts
                .into_iter()
                .max_by_key(|&(_, count)| count)
                .map(|(pair, _)| pair)
                .unwrap();

            let merged = format!("{}{}", best_pair.0, best_pair.1);
            let next_id = vocab.len();
            vocab.insert(merged.clone(), next_id);
            merges.push(best_pair.clone());

            // Apply merge to all word representations
            let mut new_word_freqs: HashMap<Vec<String>, usize> = HashMap::new();
            for (tokens, freq) in word_freqs {
                let mut new_tokens = Vec::new();
                let mut i = 0;
                while i < tokens.len() {
                    if i + 1 < tokens.len()
                        && tokens[i] == best_pair.0
                        && tokens[i + 1] == best_pair.1
                    {
                        new_tokens.push(merged.clone());
                        i += 2;
                    } else {
                        new_tokens.push(tokens[i].clone());
                        i += 1;
                    }
                }
                *new_word_freqs.entry(new_tokens).or_insert(0) += freq;
            }
            word_freqs = new_word_freqs;
        }

        let vocab_size = vocab.len();
        Self {
            vocab,
            merges,
            vocab_size,
        }
    }

    /// Tokenizes a word using the learned BPE merge rules.
    pub fn encode(&self, text: &str) -> Vec<String> {
        let word = text.to_lowercase();
        let mut tokens: Vec<String> = word.chars().map(|c| c.to_string()).collect();
        tokens.push("</w>".to_string());

        for (a, b) in &self.merges {
            let merged = format!("{}{}", a, b);
            let mut new_tokens = Vec::new();
            let mut i = 0;
            while i < tokens.len() {
                if i + 1 < tokens.len() && &tokens[i] == a && &tokens[i + 1] == b {
                    new_tokens.push(merged.clone());
                    i += 2;
                } else {
                    new_tokens.push(tokens[i].clone());
                    i += 1;
                }
            }
            tokens = new_tokens;
        }

        tokens
    }

    /// Reconstructs the original word from BPE tokens.
    pub fn decode(&self, tokens: &[String]) -> String {
        let text = tokens.join("");
        text.replace("</w>", " ").trim().to_string()
    }
}

/// Tokenizes text using the default [`TextProcessor`] settings.
pub fn load_text_data(text: &str) -> Vec<Vec<String>> {
    let processor = TextProcessor::default();
    processor.process_text(text)
}

/// Tokenizes text using a custom [`TextProcessor`].
pub fn load_text_data_advanced(text: &str, processor: &TextProcessor) -> Vec<Vec<String>> {
    processor.process_text(text)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_vocab() {
        let sentences = vec![
            vec!["hello".to_string(), "world".to_string()],
            vec!["hello".to_string(), "rust".to_string()],
        ];
        
        let (vocab, reverse_vocab) = build_vocab(&sentences);
        
        assert_eq!(vocab.len(), 3);
        assert_eq!(reverse_vocab.len(), 3);
        assert_eq!(vocab.get("hello"), Some(&0));
        assert_eq!(vocab.get("world"), Some(&1));
        assert_eq!(vocab.get("rust"), Some(&2));
    }

    #[test]
    fn test_load_text_data() {
        let text = "Hello world! This is a test.";
        let sentences = load_text_data(text);

        assert_eq!(sentences.len(), 2);
        assert_eq!(sentences[0], vec!["hello", "world"]);
        assert_eq!(sentences[1], vec!["this", "is", "a", "test"]);
    }

    fn make_test_data() -> TrainingData {
        let text = "the cat sat on the mat. the dog sat on the log. the cat chased the dog.";
        let sentences = load_text_data(text);
        let (vocab, reverse_vocab) = build_vocab(&sentences);
        TrainingData { sentences, vocab, reverse_vocab }
    }

    fn test_config(model_type: ModelType) -> TrainingConfig {
        TrainingConfig {
            embedding_dim: 8,
            learning_rate: 0.1,
            epochs: 2,
            batch_size: 4,
            context_window: 1,
            negative_samples: 2,
            model_type,
            lr_schedule: LearningRateSchedule::Constant,
            early_stopping: None,
            l2_regularization: None,
            dropout_rate: None,
            gradient_clip: None,
        }
    }

    #[test]
    fn test_train_skipgram() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config, data.vocab.len());

        assert!(model.train(&data).is_ok());

        // Embeddings should exist for known words
        assert!(model.get_embedding("cat", &data).is_some());
        assert!(model.get_embedding("dog", &data).is_some());
        assert!(model.get_embedding("the", &data).is_some());

        // Similarity should return a value for known pairs
        assert!(model.similarity("cat", "dog", &data).is_some());
    }

    #[test]
    fn test_train_cbow() {
        let data = make_test_data();
        let config = test_config(ModelType::Cbow);
        let mut model = EmbeddingModel::new(config, data.vocab.len());

        assert!(model.train(&data).is_ok());

        assert!(model.get_embedding("cat", &data).is_some());
        assert!(model.get_embedding("dog", &data).is_some());
        assert!(model.similarity("cat", "dog", &data).is_some());
    }

    #[test]
    fn test_save_embeddings() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config, data.vocab.len());
        model.train(&data).unwrap();

        let temp_dir = std::env::temp_dir();
        let path = temp_dir.join("test_embeddings_save.txt");
        let path_str = path.to_str().unwrap();

        assert!(model.save_embeddings(path_str, &data).is_ok());
        let contents = std::fs::read_to_string(path_str).unwrap();
        assert!(contents.contains("cat"));
        assert!(contents.contains("dog"));

        std::fs::remove_file(path_str).ok();
    }

    #[test]
    fn test_similarity_unknown_word() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config, data.vocab.len());
        model.train(&data).unwrap();

        assert!(model.similarity("cat", "nonexistent", &data).is_none());
        assert!(model.similarity("nonexistent", "dog", &data).is_none());
    }

    #[test]
    fn test_strip_html() {
        let processor = TextProcessor {
            remove_html: true,
            remove_punctuation: false,
            lowercase: false,
            ..TextProcessor::default()
        };
        let text = "<p>Hello world!</p> This is a <b>test</b>.";
        let sentences = processor.process_text(text);
        assert_eq!(sentences.len(), 2);
        assert_eq!(sentences[0], vec!["Hello", "world"]);
        assert_eq!(sentences[1], vec!["This", "is", "a", "test"]);
    }

    #[test]
    fn test_strip_urls() {
        let processor = TextProcessor {
            remove_urls: true,
            remove_punctuation: true,
            lowercase: true,
            ..TextProcessor::default()
        };
        let text = "Visit https://example.com for info. See www.test.org too.";
        let sentences = processor.process_text(text);
        assert_eq!(sentences.len(), 2);
        assert_eq!(sentences[0], vec!["visit", "for", "info"]);
        assert_eq!(sentences[1], vec!["see", "too"]);
    }

    #[test]
    fn test_expand_contractions() {
        let processor = TextProcessor {
            expand_contractions: true,
            remove_punctuation: true,
            lowercase: true,
            ..TextProcessor::default()
        };
        let text = "I can't do this. It's a test.";
        let sentences = processor.process_text(text);
        assert_eq!(sentences.len(), 2);
        // "can't" -> "cannot", then punctuation stripped
        assert_eq!(sentences[0], vec!["i", "cannot", "do", "this"]);
        assert_eq!(sentences[1], vec!["it", "is", "a", "test"]);
    }

    #[test]
    fn test_normalize_embeddings() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config, data.vocab.len());
        model.train(&data).unwrap();
        model.normalize_embeddings();

        for row in model.embeddings.rows() {
            let norm = row.iter().map(|&x| x * x).sum::<f32>().sqrt();
            assert!((norm - 1.0).abs() < 1e-5 || norm == 0.0);
        }
    }

    #[test]
    fn test_analogy_unknown_word() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config, data.vocab.len());
        model.train(&data).unwrap();

        assert!(model.analogy("unknown", "cat", "dog", &data, 1).is_empty());
    }

    #[test]
    fn test_split_data() {
        let sentences = vec![
            vec!["a".to_string()],
            vec!["b".to_string()],
            vec!["c".to_string()],
            vec!["d".to_string()],
            vec!["e".to_string()],
            vec!["f".to_string()],
            vec!["g".to_string()],
            vec!["h".to_string()],
            vec!["i".to_string()],
            vec!["j".to_string()],
        ];
        let config = test_config(ModelType::SkipGram);
        let model = EmbeddingModel::new(config, 1);
        let (train, val) = model.split_data(&sentences, 0.7);
        assert_eq!(train.len(), 7);
        assert_eq!(val.len(), 3);
    }

    #[test]
    fn test_gradient_clipping() {
        let data = make_test_data();
        let mut config = test_config(ModelType::SkipGram);
        config.gradient_clip = Some(0.001);
        let mut model = EmbeddingModel::new(config, data.vocab.len());

        // Training should still succeed with aggressive clipping
        assert!(model.train(&data).is_ok());
        assert!(model.get_embedding("cat", &data).is_some());
    }

    #[test]
    fn test_mini_batch_processing() {
        let data = make_test_data();
        // Test with batch_size = 1 (equivalent to old behavior)
        let mut config1 = test_config(ModelType::SkipGram);
        config1.batch_size = 1;
        let mut model1 = EmbeddingModel::new(config1, data.vocab.len());
        assert!(model1.train(&data).is_ok());

        // Test with batch_size = 8 (actual mini-batch)
        let mut config8 = test_config(ModelType::SkipGram);
        config8.batch_size = 8;
        let mut model8 = EmbeddingModel::new(config8, data.vocab.len());
        assert!(model8.train(&data).is_ok());

        // Both should produce embeddings for known words
        assert!(model1.get_embedding("cat", &data).is_some());
        assert!(model8.get_embedding("cat", &data).is_some());
    }

    #[test]
    fn test_empty_text() {
        let sentences = load_text_data("");
        assert!(sentences.is_empty());
    }

    #[test]
    fn test_single_word_text() {
        let sentences = load_text_data("hello");
        assert_eq!(sentences.len(), 1);
        assert_eq!(sentences[0], vec!["hello"]);
    }

    #[test]
    fn test_learning_rate_schedules() {
        let data = make_test_data();

        let mut config_exp = test_config(ModelType::SkipGram);
        config_exp.lr_schedule = LearningRateSchedule::Exponential { decay_rate: 0.9 };
        let mut model_exp = EmbeddingModel::new(config_exp, data.vocab.len());
        assert!(model_exp.train(&data).is_ok());

        let mut config_step = test_config(ModelType::SkipGram);
        config_step.lr_schedule = LearningRateSchedule::Step { step_size: 1, gamma: 0.5 };
        let mut model_step = EmbeddingModel::new(config_step, data.vocab.len());
        assert!(model_step.train(&data).is_ok());

        let mut config_cos = test_config(ModelType::SkipGram);
        config_cos.lr_schedule = LearningRateSchedule::Cosine { t_max: 2 };
        let mut model_cos = EmbeddingModel::new(config_cos, data.vocab.len());
        assert!(model_cos.train(&data).is_ok());
    }

    #[test]
    fn test_early_stopping() {
        let data = make_test_data();
        let mut config = test_config(ModelType::SkipGram);
        config.early_stopping = Some(EarlyStoppingConfig { patience: 1, min_delta: 0.001 });
        config.epochs = 10;
        let mut model = EmbeddingModel::new(config, data.vocab.len());
        assert!(model.train(&data).is_ok());
    }

    #[test]
    fn test_word2vec_format_roundtrip() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config, data.vocab.len());
        model.train(&data).unwrap();

        let temp_path = std::env::temp_dir().join("test_word2vec.txt");
        let path_str = temp_path.to_str().unwrap();

        // Save in Word2Vec format
        assert!(model.save_word2vec_format(path_str, &data).is_ok());

        // Load and verify
        let (loaded, dim) = EmbeddingModel::load_word2vec_format(path_str).unwrap();
        assert_eq!(dim, 8);
        assert!(loaded.contains_key("cat"));
        assert!(loaded.contains_key("dog"));
        assert_eq!(loaded.get("cat").unwrap().len(), 8);
        assert_eq!(loaded.get("dog").unwrap().len(), 8);

        std::fs::remove_file(path_str).ok();
    }

    #[test]
    fn test_bpe_tokenizer() {
        let corpus = vec![
            "low".to_string(),
            "lower".to_string(),
            "lowest".to_string(),
            "newer".to_string(),
            "new".to_string(),
            "widest".to_string(),
            "wide".to_string(),
        ];

        let tokenizer = BPETokenizer::train(&corpus, 20);

        // Vocab should have grown beyond initial character count
        assert!(tokenizer.vocab.len() >= 10);

        // Encode a word
        let tokens = tokenizer.encode("lowest");
        assert!(!tokens.is_empty());

        // Decode should reconstruct the original (with end-of-word marker removed)
        let decoded = tokenizer.decode(&tokens);
        assert_eq!(decoded, "lowest");
    }

    #[test]
    fn test_pretrained_embeddings_loading() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);

        // Create a fake pre-trained embeddings file
        let temp_path = std::env::temp_dir().join("test_pretrained.txt");
        let path_str = temp_path.to_str().unwrap();

        let mut file = std::fs::File::create(path_str).unwrap();
        use std::io::Write;
        writeln!(file, "{} {}", data.vocab.len(), config.embedding_dim).unwrap();
        for (word_id, word) in data.reverse_vocab.iter().enumerate() {
            let vals: Vec<String> = (0..config.embedding_dim)
                .map(|i| format!("{:.6}", (word_id * 10 + i) as f32 * 0.1))
                .collect();
            writeln!(file, "{} {}", word, vals.join(" ")).unwrap();
        }
        drop(file);

        // Load pre-trained embeddings
        let model = EmbeddingModel::new_with_pretrained(
            config,
            data.vocab.len(),
            &data,
            path_str,
        );
        assert!(model.is_ok());

        let model = model.unwrap();
        // Verify "cat" embedding matches pre-trained values
        let cat_emb = model.get_embedding("cat", &data).unwrap();
        let cat_id = data.vocab.get("cat").unwrap();
        for (i, &val) in cat_emb.iter().enumerate() {
            let expected = (*cat_id * 10 + i) as f32 * 0.1;
            assert!((val - expected).abs() < 1e-5, "Mismatch at index {}: got {}, expected {}", i, val, expected);
        }

        std::fs::remove_file(path_str).ok();
    }

    #[test]
    fn test_semantic_search() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config, data.vocab.len());
        model.train(&data).unwrap();

        let results = model.semantic_search("cat", &data, 5);
        assert!(!results.is_empty());
        // Results should not include the query word itself
        for (word, _) in &results {
            assert_ne!(word, "cat");
        }
    }

    #[test]
    fn test_embedding_arithmetic() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config.clone(), data.vocab.len());
        model.train(&data).unwrap();

        let result = model.embedding_arithmetic("cat", "dog", &data);
        assert!(result.is_some());
        assert_eq!(result.unwrap().len(), config.embedding_dim);
    }

    #[test]
    fn test_interpolate_embeddings() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config.clone(), data.vocab.len());
        model.train(&data).unwrap();

        let result = model.interpolate_embeddings("cat", "dog", &data, 0.5);
        assert!(result.is_some());
        assert_eq!(result.unwrap().len(), config.embedding_dim);
    }

    #[test]
    fn test_save_numpy_format() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config, data.vocab.len());
        model.train(&data).unwrap();

        let temp_path = std::env::temp_dir().join("test_numpy.npy");
        let path_str = temp_path.to_str().unwrap();

        assert!(model.save_numpy_format(path_str, &data).is_ok());

        // Verify file exists and has non-zero size
        let metadata = std::fs::metadata(path_str).unwrap();
        assert!(metadata.len() > 0);

        std::fs::remove_file(path_str).ok();
    }

    #[test]
    fn test_stream_sentences() {
        use std::io::Write;

        let temp_path = std::env::temp_dir().join("test_stream.txt");
        let path_str = temp_path.to_str().unwrap();

        let mut file = std::fs::File::create(path_str).unwrap();
        writeln!(file, "the cat sat on the mat.").unwrap();
        writeln!(file, "the dog sat on the log.").unwrap();
        writeln!(file, "the cat chased the dog.").unwrap();
        drop(file);

        let loader = DataLoader::new(4, false, false);
        let sentences: Vec<Vec<String>> = loader.stream_sentences(path_str).unwrap().collect();
        assert!(!sentences.is_empty());
        // Each line should produce tokens
        assert!(sentences.iter().all(|s| !s.is_empty()));

        std::fs::remove_file(path_str).ok();
    }

    #[test]
    fn test_incremental_vocab_update() {
        let mut data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config.clone(), data.vocab.len());
        model.train(&data).unwrap();

        let old_vocab_size = data.vocab.len();
        let old_emb_rows = model.embeddings.nrows();

        let new_words = vec!["elephant".to_string(), "giraffe".to_string()];
        let added = model.incremental_vocab_update(&new_words, &mut data).unwrap();

        assert_eq!(added.len(), 2);
        assert_eq!(data.vocab.len(), old_vocab_size + 2);
        assert_eq!(model.embeddings.nrows(), old_emb_rows + 2);
        assert_eq!(model.embeddings.ncols(), config.embedding_dim);

        // New words should be retrievable
        assert!(model.get_embedding("elephant", &data).is_some());
        assert!(model.get_embedding("giraffe", &data).is_some());
        // Existing words should still work
        assert!(model.get_embedding("cat", &data).is_some());
    }

    #[test]
    fn test_lsh_index() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config.clone(), data.vocab.len());
        model.train(&data).unwrap();

        let mut lsh = LSHIndex::new(4, config.embedding_dim);
        lsh.build(&model, &data);

        let results = lsh.query("cat", &model, &data, 5);
        // LSH may return empty if all hashes collide poorly on tiny vocab, but
        // with 4 tables and 32 bits it should usually find candidates.
        // At minimum it should not panic.
        for (word, _) in &results {
            assert_ne!(word, "cat");
        }
    }

    #[test]
    fn test_save_onnx_format() {
        use prost::Message;

        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config, data.vocab.len());
        model.train(&data).unwrap();

        let temp_path = std::env::temp_dir().join("test_model.onnx");
        let path_str = temp_path.to_str().unwrap();

        assert!(model.save_onnx_format(path_str, &data).is_ok());

        // Verify file exists and has reasonable size (protobuf header + data)
        let metadata = std::fs::metadata(path_str).unwrap();
        assert!(metadata.len() > 50);

        // Verify it's valid protobuf by decoding
        let bytes = std::fs::read(path_str).unwrap();
        let decoded = onnx::ModelProto::decode(&bytes[..]);
        assert!(decoded.is_ok());

        let m = decoded.unwrap();
        assert_eq!(m.ir_version, 9);
        assert_eq!(m.producer_name, "embedding-trainer");
        let graph = m.graph.unwrap();
        assert_eq!(graph.name, "embedding_graph");
        assert_eq!(graph.node.len(), 1);
        assert_eq!(graph.node[0].op_type, "Gather");
        assert_eq!(graph.initializer.len(), 1);

        std::fs::remove_file(path_str).ok();
    }

    #[test]
    fn test_sentence_embedding() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config.clone(), data.vocab.len());
        model.train(&data).unwrap();

        let sentence = vec!["the".to_string(), "cat".to_string(), "sat".to_string()];
        let emb = model.sentence_embedding(&sentence, &data);
        assert!(emb.is_some());
        let emb = emb.unwrap();
        assert_eq!(emb.len(), config.embedding_dim);

        // Empty sentence should return None
        assert!(model.sentence_embedding(&[], &data).is_none());
    }

    #[test]
    fn test_multimodal_fusion() {
        let text = Array::from_vec(vec![1.0, 2.0, 3.0]);
        let aux = Array::from_vec(vec![4.0, 5.0, 6.0]);
        let fusion = MultimodalFusion { text_dim: 3, aux_dim: 3 };

        // Concatenation
        let concat = fusion.concatenate(&text, &aux);
        assert_eq!(concat.len(), 6);
        assert_eq!(concat[0], 1.0);
        assert_eq!(concat[5], 6.0);

        // Weighted average (same dims)
        let avg = fusion.weighted_average(&text, &aux, 0.5).unwrap();
        assert_eq!(avg.len(), 3);
        assert!((avg[0] - 2.5).abs() < 1e-6);

        // Mismatched dims should return None
        let short = Array::from_vec(vec![1.0, 2.0]);
        assert!(fusion.weighted_average(&text, &short, 0.5).is_none());
    }

    #[test]
    fn test_cross_lingual_aligner() {
        let dim = 4;
        let mut aligner = CrossLingualAligner::new(dim);

        // Identity projection should preserve vectors
        let v = Array::from_vec(vec![1.0, 2.0, 3.0, 4.0]);
        let aligned = aligner.align(&v);
        assert_eq!(aligned, v);

        // Train on a single synthetic pair: src -> tgt = src * 2
        let src = Array::from_vec(vec![1.0, 0.0, 0.0, 0.0]);
        let tgt = Array::from_vec(vec![2.0, 0.0, 0.0, 0.0]);
        aligner.train_from_dictionary(&[(src, tgt)], 100, 0.1);

        // After training, projecting [1,0,0,0] should be close to [2,0,0,0]
        let test = Array::from_vec(vec![1.0, 0.0, 0.0, 0.0]);
        let result = aligner.align(&test);
        assert!((result[0] - 2.0).abs() < 0.1, "Expected ~2.0, got {}", result[0]);
    }

    #[test]
    fn test_domain_adapter() {
        let mut data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config.clone(), data.vocab.len());
        model.train(&data).unwrap();

        let domain_sentences = vec![
            vec!["the".to_string(), "cat".to_string()],
            vec!["a".to_string(), "dog".to_string()],
        ];
        assert!(DomainAdapter::adapt(&mut model, &mut data, &domain_sentences, 1).is_ok());
        // Domain words should now be in vocab
        assert!(data.vocab.contains_key("cat"));
    }

    #[test]
    fn test_document_embedder() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config.clone(), data.vocab.len());
        model.train(&data).unwrap();

        let sentences = vec![
            vec!["the".to_string(), "cat".to_string()],
            vec!["a".to_string(), "dog".to_string()],
        ];
        let doc = DocumentEmbedder::embed_document(&model, &data, &sentences);
        assert!(doc.is_some());
        assert_eq!(doc.unwrap().len(), config.embedding_dim);

        assert!(DocumentEmbedder::embed_document(&model, &data, &[]).is_none());
    }

    #[test]
    fn test_zero_shot_transfer() {
        let proto_a = Array::from_vec(vec![1.0, 0.0, 0.0]);
        let proto_b = Array::from_vec(vec![0.0, 1.0, 0.0]);
        let mut prototypes = HashMap::new();
        prototypes.insert("class_a".to_string(), proto_a);
        prototypes.insert("class_b".to_string(), proto_b);

        let query = Array::from_vec(vec![0.9, 0.1, 0.0]);
        let result = ZeroShotTransfer::classify(&query, &prototypes);
        assert!(result.is_some());
        let (label, sim) = result.unwrap();
        assert_eq!(label, "class_a");
        assert!(sim > 0.9);
    }

    #[test]
    fn test_query_expander() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config, data.vocab.len());
        model.train(&data).unwrap();

        let expanded = QueryExpander::expand(&model, &data, "cat", 3);
        assert!(!expanded.is_empty());
        assert_eq!(expanded[0], "cat");
    }

    #[test]
    fn test_hierarchical_clustering() {
        let data = make_test_data();
        let config = test_config(ModelType::SkipGram);
        let mut model = EmbeddingModel::new(config, data.vocab.len());
        model.train(&data).unwrap();

        let clusters = HierarchicalClustering::cluster(&model, &data, 2);
        assert_eq!(clusters.len(), 2);
        // Every vocab word should belong to exactly one cluster
        let mut all_words = std::collections::HashSet::new();
        for c in &clusters {
            for word in c {
                assert!(all_words.insert(word.clone()));
            }
        }
        assert_eq!(all_words.len(), data.vocab.len());
    }
}